DROP SEQUENCE MOVIE_SEQ;
CREATE SEQUENCE MOVIE_SEQ NOCACHE;

DROP TABLE MOVIE;
CREATE TABLE MOVIE (
    NO NUMBER NOT NULL,
    TITLE       VARCHAR2(100 BYTE),
    GENRE       VARCHAR2(100 BYTE),
    DESCRIPTION VARCHAR2(500 BYTE),
    STAR        NUMBER,
    CONSTRAINT PK_MOVIE PRIMARY KEY(NO)
);